/**
 * ingredientsList.js — 200+ Indian ingredients with categories.
 * Used for autocomplete in the smart ingredient add form.
 */

export const INGREDIENTS_LIST = [
  // ── SPICES ────────────────────────────────────────────────────────────────
  { name: "Cumin seeds",                   category: "spices" },
  { name: "Coriander seeds",               category: "spices" },
  { name: "Turmeric powder",               category: "spices" },
  { name: "Red chilli powder",             category: "spices" },
  { name: "Garam masala",                  category: "spices" },
  { name: "Cumin powder",                  category: "spices" },
  { name: "Coriander powder",              category: "spices" },
  { name: "Black pepper",                  category: "spices" },
  { name: "Cardamom",                      category: "spices" },
  { name: "Cinnamon",                      category: "spices" },
  { name: "Cloves",                        category: "spices" },
  { name: "Bay leaves",                    category: "spices" },
  { name: "Mustard seeds",                 category: "spices" },
  { name: "Fenugreek seeds",               category: "spices" },
  { name: "Asafoetida",                    category: "spices" },
  { name: "Dried red chilli",              category: "spices" },
  { name: "Kashmiri chilli powder",        category: "spices" },
  { name: "Amchur powder",                 category: "spices" },
  { name: "Chaat masala",                  category: "spices" },
  { name: "Biryani masala",                category: "spices" },
  { name: "Pav bhaji masala",              category: "spices" },
  { name: "Sambar powder",                 category: "spices" },
  { name: "Rasam powder",                  category: "spices" },
  { name: "Kitchen king masala",           category: "spices" },
  { name: "Star anise",                    category: "spices" },
  { name: "Mace",                          category: "spices" },
  { name: "Nutmeg",                        category: "spices" },
  { name: "Saffron",                       category: "spices" },
  { name: "Carom seeds",                   category: "spices" },
  { name: "Fennel seeds",                  category: "spices" },
  { name: "Nigella seeds",                 category: "spices" },
  { name: "Kasuri methi",                  category: "spices" },
  { name: "Tamarind",                      category: "spices" },
  { name: "Curry leaves",                  category: "spices" },
  { name: "Tandoori masala",               category: "spices" },
  { name: "Pepper powder",                 category: "spices" },
  { name: "Chole masala",                  category: "spices" },

  // ── LENTILS ───────────────────────────────────────────────────────────────
  { name: "Toor dal",                      category: "lentils" },
  { name: "Moong dal",                     category: "lentils" },
  { name: "Chana dal",                     category: "lentils" },
  { name: "Urad dal",                      category: "lentils" },
  { name: "Masoor dal",                    category: "lentils" },
  { name: "Rajma",                         category: "lentils" },
  { name: "Chickpeas",                     category: "lentils" },
  { name: "Black-eyed peas",               category: "lentils" },
  { name: "Whole moong",                   category: "lentils" },
  { name: "Whole urad",                    category: "lentils" },
  { name: "Moth beans",                    category: "lentils" },
  { name: "Horse gram",                    category: "lentils" },
  { name: "Yellow moong dal",              category: "lentils" },
  { name: "Red masoor dal",                category: "lentils" },
  { name: "Kabuli chana",                  category: "lentils" },
  { name: "Kala chana",                    category: "lentils" },
  { name: "Lobia",                         category: "lentils" },
  { name: "Val dal",                       category: "lentils" },

  // ── VEGETABLES ────────────────────────────────────────────────────────────
  { name: "Onion",                         category: "vegetables" },
  { name: "Tomato",                        category: "vegetables" },
  { name: "Potato",                        category: "vegetables" },
  { name: "Garlic",                        category: "vegetables" },
  { name: "Ginger",                        category: "vegetables" },
  { name: "Green chilli",                  category: "vegetables" },
  { name: "Capsicum",                      category: "vegetables" },
  { name: "Cauliflower",                   category: "vegetables" },
  { name: "Cabbage",                       category: "vegetables" },
  { name: "Carrot",                        category: "vegetables" },
  { name: "French beans",                  category: "vegetables" },
  { name: "Green peas",                    category: "vegetables" },
  { name: "Brinjal",                       category: "vegetables" },
  { name: "Okra",                          category: "vegetables" },
  { name: "Spinach",                       category: "vegetables" },
  { name: "Methi leaves",                  category: "vegetables" },
  { name: "Coriander leaves",              category: "vegetables" },
  { name: "Drumstick",                     category: "vegetables" },
  { name: "Raw banana",                    category: "vegetables" },
  { name: "Yam",                           category: "vegetables" },
  { name: "Colocasia",                     category: "vegetables" },
  { name: "Bottle gourd",                  category: "vegetables" },
  { name: "Ridge gourd",                   category: "vegetables" },
  { name: "Bitter gourd",                  category: "vegetables" },
  { name: "Snake gourd",                   category: "vegetables" },
  { name: "Ash gourd",                     category: "vegetables" },
  { name: "Pumpkin",                       category: "vegetables" },
  { name: "Sweet potato",                  category: "vegetables" },
  { name: "Radish",                        category: "vegetables" },
  { name: "Beetroot",                      category: "vegetables" },
  { name: "Corn",                          category: "vegetables" },
  { name: "Mushroom",                      category: "vegetables" },
  { name: "Zucchini",                      category: "vegetables" },
  { name: "Spring onion",                  category: "vegetables" },
  { name: "Banana flower",                 category: "vegetables" },
  { name: "Jackfruit",                     category: "vegetables" },
  { name: "Raw mango",                     category: "vegetables" },
  { name: "Cucumber",                      category: "vegetables" },
  { name: "Drumstick leaves",              category: "vegetables" },
  { name: "Amaranth leaves",               category: "vegetables" },
  { name: "Pointed gourd",                 category: "vegetables" },
  { name: "Ivy gourd",                     category: "vegetables" },
  { name: "Cluster beans",                 category: "vegetables" },
  { name: "Lotus stem",                    category: "vegetables" },
  { name: "Leek",                          category: "vegetables" },
  { name: "Celery",                        category: "vegetables" },
  { name: "Broccoli",                      category: "vegetables" },
  { name: "Baby corn",                     category: "vegetables" },

  // ── FRUITS ────────────────────────────────────────────────────────────────
  { name: "Lemon",                         category: "fruits" },
  { name: "Lime",                          category: "fruits" },
  { name: "Banana",                        category: "fruits" },
  { name: "Apple",                         category: "fruits" },
  { name: "Mango",                         category: "fruits" },
  { name: "Papaya",                        category: "fruits" },
  { name: "Pomegranate",                   category: "fruits" },
  { name: "Orange",                        category: "fruits" },
  { name: "Coconut",                       category: "fruits" },
  { name: "Amla",                          category: "fruits" },
  { name: "Guava",                         category: "fruits" },
  { name: "Pineapple",                     category: "fruits" },
  { name: "Dates",                         category: "fruits" },
  { name: "Raisins",                       category: "fruits" },
  { name: "Watermelon",                    category: "fruits" },
  { name: "Grapes",                        category: "fruits" },
  { name: "Pear",                          category: "fruits" },
  { name: "Chikoo",                        category: "fruits" },
  { name: "Custard apple",                 category: "fruits" },

  // ── OILS ──────────────────────────────────────────────────────────────────
  { name: "Sunflower oil",                 category: "oils" },
  { name: "Coconut oil",                   category: "oils" },
  { name: "Mustard oil",                   category: "oils" },
  { name: "Groundnut oil",                 category: "oils" },
  { name: "Sesame oil",                    category: "oils" },
  { name: "Olive oil",                     category: "oils" },
  { name: "Ghee",                          category: "oils" },
  { name: "Butter",                        category: "oils" },
  { name: "Refined oil",                   category: "oils" },
  { name: "Rice bran oil",                 category: "oils" },
  { name: "Vanaspati",                     category: "oils" },

  // ── FLOURS ────────────────────────────────────────────────────────────────
  { name: "Wheat flour",                   category: "flours" },
  { name: "Maida",                         category: "flours" },
  { name: "Besan",                         category: "flours" },
  { name: "Rice flour",                    category: "flours" },
  { name: "Ragi flour",                    category: "flours" },
  { name: "Jowar flour",                   category: "flours" },
  { name: "Bajra flour",                   category: "flours" },
  { name: "Cornflour",                     category: "flours" },
  { name: "Semolina",                      category: "flours" },
  { name: "Poha",                          category: "flours" },
  { name: "Bread crumbs",                  category: "flours" },
  { name: "Oat flour",                     category: "flours" },
  { name: "Rajgira flour",                 category: "flours" },
  { name: "Sabudana",                      category: "flours" },
  { name: "Arrowroot powder",              category: "flours" },

  // ── DAIRY ─────────────────────────────────────────────────────────────────
  { name: "Milk",                          category: "dairy" },
  { name: "Curd",                          category: "dairy" },
  { name: "Paneer",                        category: "dairy" },
  { name: "Cheese",                        category: "dairy" },
  { name: "Cream",                         category: "dairy" },
  { name: "Condensed milk",                category: "dairy" },
  { name: "Khoya",                         category: "dairy" },
  { name: "Buttermilk",                    category: "dairy" },
  { name: "Coconut milk",                  category: "dairy" },
  { name: "Milk powder",                   category: "dairy" },
  { name: "Heavy cream",                   category: "dairy" },
  { name: "Malai",                         category: "dairy" },

  // ── PROTEIN ───────────────────────────────────────────────────────────────
  { name: "Chicken",                       category: "protein" },
  { name: "Mutton",                        category: "protein" },
  { name: "Fish",                          category: "protein" },
  { name: "Eggs",                          category: "protein" },
  { name: "Prawn",                         category: "protein" },
  { name: "Crab",                          category: "protein" },
  { name: "Soya chunks",                   category: "protein" },
  { name: "Tofu",                          category: "protein" },
  { name: "Lamb",                          category: "protein" },
  { name: "Chicken breast",                category: "protein" },
  { name: "Chicken thigh",                 category: "protein" },
  { name: "Minced meat",                   category: "protein" },
  { name: "Sardine",                       category: "protein" },
  { name: "Tuna",                          category: "protein" },

  // ── GRAINS ────────────────────────────────────────────────────────────────
  { name: "Basmati rice",                  category: "grains" },
  { name: "Regular rice",                  category: "grains" },
  { name: "Brown rice",                    category: "grains" },
  { name: "Parboiled rice",                category: "grains" },
  { name: "Broken wheat",                  category: "grains" },
  { name: "Quinoa",                        category: "grains" },
  { name: "Flattened rice",                category: "grains" },
  { name: "Oats",                          category: "grains" },
  { name: "Barley",                        category: "grains" },
  { name: "Ragi",                          category: "grains" },
  { name: "Jowar",                         category: "grains" },
  { name: "Bajra",                         category: "grains" },
  { name: "Maize",                         category: "grains" },
  { name: "Sago",                          category: "grains" },
  { name: "Vermicelli",                    category: "grains" },
  { name: "Pasta",                         category: "grains" },
  { name: "Noodles",                       category: "grains" },

  // ── OTHER ─────────────────────────────────────────────────────────────────
  { name: "Salt",                          category: "other" },
  { name: "Sugar",                         category: "other" },
  { name: "Jaggery",                       category: "other" },
  { name: "Honey",                         category: "other" },
  { name: "Baking soda",                   category: "other" },
  { name: "Baking powder",                 category: "other" },
  { name: "Yeast",                         category: "other" },
  { name: "Vinegar",                       category: "other" },
  { name: "Soy sauce",                     category: "other" },
  { name: "Tomato ketchup",               category: "other" },
  { name: "Green chutney",                 category: "other" },
  { name: "Red chilli sauce",              category: "other" },
  { name: "Desiccated coconut",            category: "other" },
  { name: "Cashews",                       category: "other" },
  { name: "Almonds",                       category: "other" },
  { name: "Peanuts",                       category: "other" },
  { name: "Walnuts",                       category: "other" },
  { name: "Pistachios",                    category: "other" },
  { name: "Poppy seeds",                   category: "other" },
  { name: "Sesame seeds",                  category: "other" },
  { name: "Flax seeds",                    category: "other" },
  { name: "Chia seeds",                    category: "other" },
  { name: "Rose water",                    category: "other" },
  { name: "Kewra water",                   category: "other" },
  { name: "Vanilla essence",               category: "other" },
  { name: "Cocoa powder",                  category: "other" },
  { name: "Dark chocolate",                category: "other" },
  { name: "Food colour",                   category: "other" },
  { name: "Eno",                           category: "other" },
  { name: "Tamarind paste",               category: "other" },
  { name: "Coconut water",                 category: "other" },
]

/**
 * Search ingredients by name prefix/substring.
 * Returns top 8 matches sorted by relevance (prefix match first).
 */
export function searchIngredients(query) {
  if (!query || query.trim().length < 1) return []
  const q = query.trim().toLowerCase()
  const prefixMatches = INGREDIENTS_LIST.filter(i =>
    i.name.toLowerCase().startsWith(q)
  )
  const subMatches = INGREDIENTS_LIST.filter(i =>
    !i.name.toLowerCase().startsWith(q) &&
    i.name.toLowerCase().includes(q)
  )
  return [...prefixMatches, ...subMatches].slice(0, 8)
}

/**
 * Get all ingredients for a given category.
 */
export function getByCategory(category) {
  return INGREDIENTS_LIST.filter(i => i.category === category)
}
